cookieSecret := $(shell openssl rand -base64 32 | tr -- '+/' '-_')
all:
	@echo "Usage:"
	@echo "make compose-up"
	@echo "make compose-down"
	@echo "make compose-ps"

.PHONY: docker-build
docker-build:
	docker build --no-cache -t veerash/oauth2-proxy-sample:nodeweb-app -f Dockerfile .

.PHONY: docker-push
docker-push: docker-build
	docker login
	docker push veerash/oauth2-proxy-sample:nodeweb-app

build-compose-up: docker-push
	docker-compose -f ./compose/docker-compose.yaml up -d

compose-up:	
	docker-compose -f ./compose/docker-compose.yaml up -d

compose-down:
	docker-compose -f ./compose/docker-compose.yaml down

compose-ps:
	docker-compose -f ./compose/docker-compose.yaml ps

.PHONY: helm-init
helm-init:
	helm dep update k8s/oauth2-proxy-auth0-chart

# Usage: make clientSecret="" auth0Tenant="<domain>.auth0.com" helm-deploy
helm-deploy: helm-init
	helm upgrade --wait --debug --install --render-subchart-notes \
		--set oauth2-proxy.config.cookieSecret=$(cookieSecret),oauth2-proxy.config.clientSecret=$(clientSecret),oauth2-proxy.extraEnv[0].name="OAUTH2_PROXY_OIDC_ISSUER_URL",oauth2-proxy.extraEnv[0].value=$(auth0Tenant) \
		oauth2-proxy-auth0-example k8s/oauth2-proxy-auth0-chart

helm-undeploy:
	helm del oauth2-proxy-auth0-example

# Usage: make clientSecret="" auth0Tenant="<domain>.auth0.com" helm-create-manifest
helm-create-manifest: helm-init
	echo "# WARNING: This file is auto-generated by 'make helm-create-manifest'! DO NOT EDIT MANUALLY!" > k8s/oauth2-proxy-auth0-example-full.yaml	
	helm template \
		--namespace default \
		--set-string oauth2-proxy.config.cookieSecret=$(cookieSecret),oauth2-proxy.config.clientSecret=$(clientSecret),oauth2-proxy.extraEnv[0].name="OAUTH2_PROXY_OIDC_ISSUER_URL",oauth2-proxy.extraEnv[0].value=https://$(auth0Tenant) \
		oauth2-proxy-auth0-example k8s/oauth2-proxy-auth0-chart >> k8s/oauth2-proxy-auth0-example-full.yaml