# Update OAUTH2_PROXY_OIDC_ISSUER_URL='https://<auth0 domain name>/' OAUTH2_PROXY_CLIENT_ID='auth0 clientid' OAUTH2_PROXY_CLIENT_SECRET='auth0 client secret' in oauth2-proxy.cfg
# make compose-up
# Access http://localhost:4180 to initiate a login cycle
# Once you are done validating, use 
# make compose-down
# to bring the cluster down
version: '3.0'
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    command: --config /oauth2-proxy.cfg
    env_file:
      - oauth2-proxy.env    
    ports:
      - 4180:4180/tcp
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    networks:      
      nodeweb-app: {}
      redis: {}
    depends_on:      
      - nodeweb-app
      - redis
  nodeweb-app:
    container_name: nodeweb-app
    image: veerash/oauth2-proxy-sample:nodeweb-app
    env_file:
      - oauth2-proxy.env
    ports:
      - 3000:3000/tcp
    hostname: nodeweb-app    
    networks:
      nodeweb-app: {}  
  redis:
    image: redis:7.0.2-alpine3.16
    volumes:
      - cache:/data
    networks:
      redis: {}
volumes:
  cache:
    driver: local
networks:
  nodeweb-app: {}
  redis: {}